package com.koni.telemetry.infrastructure.persistence.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * JPA entity for persisting telemetry data in the database.
 * This entity represents the write model in the CQRS pattern.
 */
@Entity
@Table(
    name = "telemetry",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_telemetry_device_date",
            columnNames = {"device_id", "date"}
        )
    },
    indexes = {
        @Index(
            name = "idx_telemetry_device_date",
            columnList = "device_id, date DESC"
        )
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TelemetryEntity {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "device_id", nullable = false)
    private Long deviceId;
    
    @Column(name = "measurement", nullable = false, precision = 10, scale = 2)
    private BigDecimal measurement;
    
    @Column(name = "date", nullable = false)
    private Instant date;
    
    @Column(name = "recorded_at", nullable = false, updatable = false)
    private Instant recordedAt;
    
    /**
     * Constructor for creating a new TelemetryEntity without ID.
     * The ID will be generated by the database.
     *
     * @param deviceId the device identifier
     * @param measurement the temperature measurement
     * @param date the timestamp of the measurement
     * @param recordedAt the timestamp when the record was created
     */
    public TelemetryEntity(Long deviceId, BigDecimal measurement, Instant date, Instant recordedAt) {
        this.deviceId = deviceId;
        this.measurement = measurement;
        this.date = date;
        this.recordedAt = recordedAt;
    }
    
    @PrePersist
    protected void onCreate() {
        if (recordedAt == null) {
            recordedAt = Instant.now();
        }
    }
}
